---

- name: Copy backend dist files to remote server
  copy:
    src: 
    dest: /home/ubuntu

- name: Untar file
  shell: |
    cd /home/ubuntu
    tar -xvzf backend.tgz

- name: Install Node modules
  shell: |
    cd /home/ubuntu/backend
    ls -la
    printenv
    npm install

- name: building node services
  shell: |
    cd /home/ubuntu/backend
    npm run build
    npm run prestart:prod

- name: "run migrations again"
  shell: |
    cd /home/ubuntu/backend
    npm run migrations
    
- name: Executing node
  become: true
  shell: |
    cd /home/ubuntu/backend 
    pm2 start npm --name backend -- start
    pm2 ls